project_id = "mggedvvzpwxlgrhatrau"

[functions.generate-style]
verify_jwt = true

[functions.cleanup-cache]
verify_jwt = false

[functions.deeplink]
verify_jwt = false

[functions.collect-products]
verify_jwt = false

[functions.cron-collect]
verify_jwt = false

[functions.test-serpapi]
verify_jwt = false

[functions.style-v1]
verify_jwt = false

[functions.style-recommend]
verify_jwt = false

[functions.brightdata-collect]
verify_jwt = false

[functions.firecrawl-test]
verify_jwt = false
