// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { z } from "npm:zod@^3.25.76";
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the ShowMeLook product catalog by keyword, category, gender, and price range. Returns active in-stock items.",
  inputSchema: {
    query: z.string().optional().describe("Free-text keyword to match against product name, brand, or tags."),
    category: z.enum(["\uC0C1\uC758", "\uD558\uC758", "\uC544\uC6B0\uD130", "\uAC00\uBC29", "\uC2E0\uBC1C", "\uC561\uC138\uC11C\uB9AC", "\uC6D0\uD53C\uC2A4", "\uD648\uC6E8\uC5B4", "\uC218\uC601\uBCF5"]).optional().describe("Standard fashion category."),
    gender: z.enum(["female", "male", "kids", "unisex"]).optional(),
    min_price: z.number().int().nonnegative().optional(),
    max_price: z.number().int().nonnegative().optional(),
    limit: z.number().int().min(1).max(50).optional().describe("Max results, default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, gender, min_price, max_price, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    let q = supabase.from("products_cache").select("id,name,brand,category,sub_category,gender,price,original_price,color,image_url,product_url,style_tags").eq("is_active", true).eq("is_in_stock", true).limit(limit ?? 10);
    if (category) q = q.eq("category", category);
    if (gender) q = q.eq("gender", gender);
    if (typeof min_price === "number") q = q.gte("price", min_price);
    if (typeof max_price === "number") q = q.lte("price", max_price);
    if (query && query.trim()) {
      const like = `%${query.trim().replace(/[%_]/g, "")}%`;
      q = q.or(`name.ilike.${like},brand.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch full details for a ShowMeLook product by ID, including brand, price, image, style tags, and the purchase URL.",
  inputSchema: {
    product_id: z2.string().uuid().describe("products_cache.id")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ product_id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("products_cache").select(
      "id,name,brand,category,sub_category,gender,price,original_price,color,image_url,product_url,style_tags,sizes,dna_text,is_active,is_in_stock"
    ).eq("id", product_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Product not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-public-looks.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_public_looks_default = defineTool3({
  name: "list_public_looks",
  title: "List public looks",
  description: "List recent public AI-generated looks from the ShowMeLook community gallery, sorted by most recent by default.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max looks to return, default 10."),
    sort: z3.enum(["recent", "popular"]).optional().describe("Sort order (default recent).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, sort }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    let q = supabase.from("generated_looks_public").select("id,image_url,caption,tags,like_count,view_count,created_at,product_ids").limit(limit ?? 10);
    q = sort === "popular" ? q.order("like_count", { ascending: false }) : q.order("created_at", { ascending: false });
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { looks: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "showmelook-mcp",
  title: "ShowMeLook MCP",
  version: "0.1.0",
  instructions: "Tools for ShowMeLook (\uC1FC\uBBF8\uB8E9), an AI virtual fitting and fashion styling service. Use `search_products` to find fashion items in the catalog, `get_product` to retrieve full details and the purchase link, and `list_public_looks` to browse recent public AI-generated looks from the community gallery.",
  tools: [search_products_default, get_product_default, list_public_looks_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
