-- Add DNA columns to products_cache for faster future recommendations
ALTER TABLE public.products_cache ADD COLUMN IF NOT EXISTS dna_text TEXT;
ALTER TABLE public.products_cache ADD COLUMN IF NOT EXISTS dna_generated_at TIMESTAMP WITH TIME ZONE;

-- Add index for faster DNA lookups
CREATE INDEX IF NOT EXISTS idx_products_cache_dna_generated ON public.products_cache(dna_generated_at) WHERE dna_text IS NOT NULL;

-- Comment for documentation
COMMENT ON COLUMN public.products_cache.dna_text IS 'Pre-computed product DNA: style tags, pros/cons, coordination tips (generated by AI)';
COMMENT ON COLUMN public.products_cache.dna_generated_at IS 'Timestamp when DNA was generated';